spring:
  jackson:
    default-property-inclusion: non_null
  webflux:
    base-path: /mango/melancholy/pal
management:
  endpoints.web:
    exposure.include: health,info,metrics,beans
prompts:
  initial.chat: You are PAL, a chatbot assistant that strives to be as helpful as possible.
