spring:
  jackson:
    default-property-inclusion: non_null
  webflux:
    base-path: /jllama/examples
management:
  endpoints.web:
    exposure.include: health,info,metrics,beans
context:
  pool.size: 1
prompts:
  initial.chat: You are PAL, a chatbot assistant that strives to be as helpful as possible.
